### ISSUE TITLE
Add ontologies for generic obo noctua instance

### ISSUE THREAD

**Issue by cmungall** [geneontology/ansible-machine-bootstrap#3]
This ticket for general notes on the ontology list for the generic obo ontology instance.

@balhoff @dosumis @jamesaoverton - which ontologies would be good ones for inclusion?

@selewis is getting the participant list for the Noctua tutorial at ICBO - http://icbo.cgrb.oregonstate.edu/node/31 - we can tune the list for the participants

**Comment by cmungall** [comment]
note to self and @kltm - currently the list needs updated in two places. Will add to noctua-obo-aws-startup.yaml for now, and then copy over to amigo

**Comment by kltm** [comment]
I'll wait a couple of day on this to give the others a chance to response (Monday?), then rebuild the servers.

**Comment by jamesaoverton** [comment]
I'd like to help, but I don't understand the context.

**Comment by cmungall** [comment]
Do you think there would be interest in being able to graphically edit ABoxes for OBI for example?

**Comment by jamesaoverton** [comment]
I'd be interested in seeing OBI in Noctua.
